version 3.0

diff --git a/inst/examples/acotsp/target-runner b/inst/examples/acotsp/target-runner
--- a/inst/examples/acotsp/target-runner
+++ b/inst/examples/acotsp/target-runner
@@ -12,30 +12,29 @@
 # RETURN VALUE:
 # This script should print a single numerical value (the value to be minimized).
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@" >&2
+    exit 1
+}
+
 
 # Path to the ACOTSP software:
 EXE=~/bin/acotsp
 
 # Fixed parameters that should be always passed to ACOTSP.
-# The time to be used is always 5 seconds, and we want only one run:
-FIXED_PARAMS=" --tries 1 --quiet "
+# The time to be used is always 10 seconds, and we want only one run:
+FIXED_PARAMS=" --tries 1 --time 10 --quiet "
 
 CONFIG_ID="$1"
 INSTANCE_ID="$2"
 SEED="$3"
 INSTANCE="$4"
 # All other parameters are the candidate parameters to be passed to program
-shift 4 || error "Not enough parameters to $0"
+shift 4 || error "Not enough parameters"
 CONFIG_PARAMS=$*
 
-STDOUT=c${CONFIG_ID}-${INSTANCE_ID}.stdout
-STDERR=c${CONFIG_ID}-${INSTANCE_ID}.stderr
-
-# In case of error, we print the current time:
-error() {
-    echo "`TZ=UTC date`: error: $@" >&2
-    exit 1
-}
+STDOUT=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stdout
+STDERR=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stderr
 
 if [ ! -x "${EXE}" ]; then
     error "${EXE}: not found or not executable (pwd: $(pwd))"
diff --git a/inst/examples/batchmode-cluster/target-evaluator b/inst/examples/batchmode-cluster/target-evaluator
--- a/inst/examples/batchmode-cluster/target-evaluator
+++ b/inst/examples/batchmode-cluster/target-evaluator
@@ -20,25 +20,25 @@
 # This script should print one numerical value: the cost that must be minimized.
 # Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@"
+    exit 1
+}
+
 CANDIDATE="$1"
 INSTANCEID="$2"
 SEED="$3"
 INSTANCE="$4"
 TOTALCANDIDATES="$5"
-shift 5 || error "Not enough parameters to $0"
+shift 5 || error "Not enough parameters"
 ALLIDS=$*
 
-STDOUT=c${CANDIDATE}-${INSTANCEID}.stdout
-STDERR=c${CANDIDATE}-${INSTANCEID}.stderr
-
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    exit 1
-}
+STDOUT=c${CANDIDATE}-${INSTANCEID}-${SEED}.stdout
+STDERR=c${CANDIDATE}-${INSTANCEID}-${SEED}.stderr
 
 ALLFILES=
 for FILENAME in $ALLIDS; do
-    ALLFILES="$ALLFILES c${FILENAME}-${INSTANCEID}.stdout"
+    ALLFILES="$ALLFILES c${FILENAME}-${INSTANCEID}-${SEED}.stdout"
 done
 
 # # This may be used to introduce a delay if there are filesystem
@@ -56,7 +56,7 @@ if [ -s "${STDOUT}" ]; then
     # You may need to update this to parse the output of your algorithm.
     COST=$(cat ${STDOUT} | grep -e '^[[:space:]]*[+-]\?[0-9]' | cut -f1)
     echo "$COST"
-    TODELETE=$(comm -23 <(ls -1 c*-${INSTANCEID}.* | sort) <(ls -1 $ALLFILES))
+    TODELETE=$(comm -23 <(ls -1 c*-${INSTANCEID}-${SEED}.* | sort) <(ls -1 $ALLFILES))
     # Comment out if you wish to keep all output files around
     echo "rm -f $TODELETE"
     exit 0
diff --git a/inst/examples/moaco/target-runner b/inst/examples/moaco/target-runner
--- a/inst/examples/moaco/target-runner
+++ b/inst/examples/moaco/target-runner
@@ -6,11 +6,17 @@
 # $2 is the instance id
 # $3 is the seed
 # $4 is the instance name
-# The rest ($* after `shift 4') are parameters to the run
+# The rest are parameters for running the program
 #
 # RETURN VALUE:
-# This script should print a single numerical value (the value to be minimized)
+# This script should print nothing.
+# Exit with 0 if no error, with 1 in case of error
 ###############################################################################
+error() {
+    echo "`TZ=UTC date`: $0: error: $@"
+    exit 1
+}
+
 # If you want to find where target-runner is.
 #BINDIR=$(dirname "$(readlink -f "$(type -P $0 || echo $0)")")
 EXE=~/bin/moaco_btsp
@@ -19,13 +25,13 @@ CONFIGURATION=$1
 INSTANCEID=$2
 SEED=$3
 INSTANCE=$4
-shift 4 || error "Not enough parameters to $0"
+shift 4 || error "Not enough parameters"
 
-STDOUT=c${CONFIGURATION}-${INSTANCEID}.stdout
-STDERR=c${CONFIGURATION}-${INSTANCEID}.stderr
+STDOUT=c${CONFIGURATION}-${INSTANCEID}-${SEED}.stdout
+STDERR=c${CONFIGURATION}-${INSTANCEID}-${SEED}.stderr
 
 # TODO: Use /tmp for all temporary files, i.e., put target-runner-data under /tmp
-tmp="./target-runner-tmp"
+tmp="./target-data"
 mkdir -p ${tmp}
 cd ${tmp} || error "cannot change to directory \'${tmp}\'"
 
@@ -54,7 +60,3 @@ RET=$?
 echo "OK" >& 2
 exit $RET
 
-error() {
-    echo "`TZ=UTC date`: error: $@"
-    exit 1
-}
